## 예외처리
### 프로그램 오류

- 프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우
- 컴파일 에러: 컴파일 시에 발생하는 에러
- 런타임 에러: 실행 시에 발생하는 에러
- 논리적 에러: 실행은 되지만, 의도와 다르게 동작하는 것
- 에러(error): 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
- 예외(exception): 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

### 예외 클래스의 계층구조

- Exception 클래스들: 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
- 예) 존재하지 않는 파일의 이름 입력(FileNotFoundException), 실수로 클래스의 이름을 잘못 입력(ClassNotFoundException), 데이터 형식 잘못 입력(DataFormatException) 등
- RuntimeException 클래스들: 프로그래머의 실수로 발생하는 예외
- 예) 배열의 범위를 벗어남(ArrayIndexOutOfBoundsException), 값이 null인 참조변수 호출(NullPointerException), 클래스간 형변환 잘못함(ClassCastException), 정수를 0으로 나누려고 함(ArithmeticException) 등

### 예외처리하기 - try-catch

- 예외처리: 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것
- 프로그램의 비정상 종료를 막고, 정상적인 실행상태 유지
- 하나의 try 블럭 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch 블록이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch 블록이 수행된다
- 발생한 예외의 종류와 일치하는 catch 블록이 없으면 예외는 처리되지 않는다

``` java
try{
//예외가 발생할 가능성이 있는 문장들을 넣는다
} catch(Exception1 e1){
// Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다
} catch(Exception2 e2){
// Exception2이 발생했을 경우, 이를 처리하기 위한 문장을 적는다
} ...
catch(ExceptionN eN){
// ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 적는다
}

```

- printStackTrace(): 예외발생 당시의 호출스택에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다
- getMessage(): 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다

### finally

- finally 블록: 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용
- try -> catch -> finally

### 예외 되던지기

- 예외를 처리한 후에 인위적으로 다시 발생시키는 방법
